download.file(url="https://spark-public.s3.amazonaws.com/dataanalysis/movies.txt",destfile="./movies.txt", method="curl")
movies <- read.table(file="./movies.txt",header=T,sep="\t",quote="")
plot(movies$box.office,movies$score,pch=19,col="blue")
head(movies)
lm1 <- lm(movies$score ~ movies$box.office)
lines(movies$box.office,lm1$fitted,col="red",lwd=3)
summary(lm1)
confint(lm1)
lmBoth <- lm(movies$score ~ movies$box.office + movies$running.time)
summary(lmBoth)
# Question 4
anova(lm(movies$score ~ movies$box.office))
anova(lm(movies$score ~ movies$running.time))
# Question 5
plot(movies$running.time ~ movies$score)
max(movies$running.time)
boxplot(movies$running.time ~ movies$score)
summary(movies$running.time)
lmBoth_sub <- lm(movies_sub$score ~ movies_sub$box.office + movies_sub$running.time)
summary(lmBoth_sub)
summary(lmBoth)